pipeline{
    agent any

    environment{
        IMAGE_NAME = "drinkapp"
        IMAGE_TAG = "dev"
        CLUSTERNAME = "drink-cluster"
        NAMESPACE = "foo"
        FINALIAMGE =  "arjunckm/${IMAGE_NAME}:${IMAGE_TAG}"
        AWS_REGION = "us-east-1"
    }

    tools{
        jdk 'java-17'
        maven 'maven'
    }

    stages{
        stage("GIT-CLONING"){
            steps{
               git url :"https://github.com/Gotoman12/ITKannadigaru-Java-based-app.git",branch: "main"
            }
        }
        stage("Build"){
            steps{
             sh 'mvn compile'
            }
        }
        stage("Package"){
            steps{
             sh 'mvn clean package'
            }
        }
        stage("Docker Build"){
           steps{
              sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
           }
        }
        stage("Docker Login"){
           steps{
             script{
                withCredentials([usernamePassword(credentialsId:"DOCKER_CRED",usernameVariable:"DOCKER_USER",passwordVariable:"DOCKER_PASS")]){
                     sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
             }
           }
        }
        stage("Docker TAG"){
           steps{
            sh 'docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${FINALIAMGE}'
           }
        }
        stage("Docker PUSH"){
           steps{
            sh 'docker push ${FINALIAMGE}'
            sh "echo Using image: ${FINALIAMGE}"
           }
        }
        stage("K8s update"){
           steps{
            sh 'aws eks update-kubeconfig --region ${AWS_REGION} --name ${CLUSTERNAME}'
           }
        }
        stage("Deploy K8s"){
            steps{
                script{
                    withKubeConfig(
                    caCertificate: '',
                    clusterName: '${CLUSTERNAME}',
                    contextName: '',
                    credentialsId: 'kube',
                    namespace: '${NAMESPACE}',
                    restrictKubeConfigAccess: false,
                    serverUrl: 'https://B8E6BC948B3311CCA4C6FB401E20EF84.gr7.us-east-1.eks.amazonaws.com'
                )
                    {
                        sh """
                            cd JenkinsBlueGreen
                            sed -i 's|replace|${FINALIAMGE}|g' bluedeployment.yaml
                            kubectl apply -f bluedeployment.yaml -n ${NAMESPACE} --timeout=600s
                            sed -i 's|replace|${FINALIAMGE}|g' greendeployment.yaml
                            kubectl apply -f greendeployment.yaml -n ${NAMESPACE} --timeout=600s
                        """
                    }
                }
            }
            post{
                success{
                   echo "Deployed the application in EKS and pipeline: PASS"

                }
                failure{
                    sh 'kubectl rollout undo deploy/drinks-app -n ${NAMESPACE}'
                }
            }
        }
        stage("Blue-Green Switch") {
    steps {
        script {
            withKubeConfig(
                    caCertificate: '',
                    clusterName: '${CLUSTERNAME}',
                    contextName: '',
                    credentialsId: 'kube',
                    namespace: '${NAMESPACE}',
                    restrictKubeConfigAccess: false,
                    serverUrl: 'https://B8E6BC948B3311CCA4C6FB401E20EF84.gr7.us-east-1.eks.amazonaws.com'
                )
              {
            // Get active color safely
            def active = sh(
                script: "kubectl get svc drinks-service -n ${NAMESPACE} -o jsonpath='{.spec.selector.version}' || echo 'none'",
                returnStdout: true
            ).trim()

            def target = (active == "blue") ? "green" : "blue"

            echo "Active color: ${active}"
            echo "Deploying to: ${target}"

            // Deploy target version
            sh """
                kubectl set image deployment/drink-${target} drinks-app=${FINALIAMGE} -n ${NAMESPACE}
                kubectl rollout status deployment/drink-${target} -n ${NAMESPACE}
            """

            // Switch traffic only after success
            sh """
                kubectl patch svc drinks-service -n ${NAMESPACE} \
                -p '{"spec":{"selector":{"app":"drinks-app","version":"${target}"}}}'
            """

            echo "Switched traffic to ${target}"
              }

        }
    }
}
          stage("Deploy Verify"){
            steps{
                script{
                    withKubeConfig(
                    caCertificate: '',
                    clusterName: '${CLUSTERNAME}',
                    contextName: '',
                    credentialsId: 'kube',
                    namespace: '${NAMESPACE}',
                    restrictKubeConfigAccess: false,
                    serverUrl: 'https://B8E6BC948B3311CCA4C6FB401E20EF84.gr7.us-east-1.eks.amazonaws.com'
                )
                    {
                        sh '''
                            kubectl get pods -n ${NAMESPACE}
                            kubectl get svc -n ${NAMESPACE}
                        '''
                    }
                }
            }
        }
    }
}